const portfolioProjects = [
    {
        title: 'Controlsep',
        slug: 'controlsep',
        categories: ["frontend","backend"],
        languages: ['React', 'Node.js', 'Express', 'MongoDB', 'Styled Components'],
        img: 'Controlsep.webp',
        description: `Control your home water and energy consumption with insightful dashboards and alerts.`,
        longDescription: `Controlsep helps households monitor and optimize water and energy usage. I designed the architecture, built the API and created a reactive UI with real‑time charts, offline storage and PWA capabilities.`,
        url: 'https://controlsep.com/'
    },
    {
        title: 'Tagmascota',
        slug: 'tagmascota',
        categories: ["backend","frontend"],
        languages: ['Next.js', 'Node.js', 'MongoDB', 'Vercel', 'Styled Components'],
        img: 'Tagmascota.webp',
        description: `A lost & found hub for pets with QR tags and instant owner contact.`,
        longDescription: `A complete solution for pet identification and recovery. Each pet has a QR code linking to a secure profile. When scanned, the system notifies owners and shares a safe contact channel.`,
        url: 'https://tagmascotas.vercel.app/',
    },
    {
        title: 'Movilidad en Línea (Quipux)',
        slug: 'movilidad-en-linea-quipux',
        categories: ["companie","backend","frontend"],
        languages: ['Vue', 'Java', 'Spring', 'Oracle', 'K8s'],
        img: 'CompanieQuipuxMovilidadEnLinea.webp',
        description: `City e‑government platform for online mobility procedures.`,
        longDescription: `A large scale portal for citizens to perform mobility procedures online. I contributed to microservices hardening, CI/CD, caching and UX improvements to reduce queue times and visits.`,
        url: 'https://www.medellin.gov.co/portal-movilidad/#/public',
    },
    {
        title: "CGI DIGITAL Côte d'Ivoire (Quipux Afrique)",
        slug: 'cgi-digital-quipux-afrique',
        categories: ["companie","backend","frontend"],
        languages: ['Angular', 'Java', 'Spring', 'PostgreSQL', 'Redis'],
        img: 'CompanieQuipuxAfrique.webp',
        description: `Integrated transport management platform for Côte d’Ivoire.`,
        longDescription: `As part of a distributed team, I worked on backend services, security hardening and API integrations to enable real‑time document issuance and nationwide service consistency.`,
        url: 'https://eservices.cgi.ci/avit/#/public',
    },
    {
        title: 'Snippets en JavaScript: optimiza tus tareas repetitivas en VSCode.',
        slug: 'blog-snippets-js',
        categories: ["blog"],
        languages: ['JavaScript'],
        img: 'BlogSnippetsJavascript.webp',
        description: `Article: Boost your productivity with custom JS snippets in VSCode.`,
        longDescription: `A practical guide to create and organize VSCode snippets that speed up everyday tasks in JavaScript projects.`,
        url: 'https://www.jhonsebastianas.com/blog/articles/snippets-en-javaScript-optimiza-tus-tareas-repetitivas-en-vscode',
    },
    {
        title: 'Un vistazo al futuro: el internet de las cosas (IOT) en el 2021 para “consumidores inteligentes”',
        slug: 'blog-iot-2021',
        categories: ["blog"],
        languages: ['IoT', 'Edge'],
        img: 'BlogUnVistazoAlFuturo.webp',
        description: `Article: Where IoT is heading and how it impacts consumers.`,
        longDescription: `An overview of IoT adoption and practical implications for consumers and businesses alike.`,
        url: 'https://medium.com/@jhonsebastianas/un-vistazo-al-futuro-el-internet-de-las-cosas-iot-en-el-2021-para-consumidores-inteligentes-f3f1375cecb5',
    },
]

export default portfolioProjects